// ── 穿搭管理器 · 样式 ──────────────────────────────────
// 全部 CSS 注入

export function injectStyles() {
    var old = document.getElementById('om-style-v4');
    if (old) old.parentNode.removeChild(old);
    var s = document.createElement('style');
    s.id = 'om-style-v4';
        s.textContent = [
            /* ══ 全屏主界面 ══ */
            '@keyframes om-fadein{from{opacity:0}to{opacity:1}}',
            '@keyframes om-sheet-up{from{transform:translateY(100%)}to{transform:translateY(0)}}',
            '@keyframes om-popin{from{opacity:0;transform:scale(.95)}to{opacity:1;transform:scale(1)}}',

            /* 全屏遮罩/容器 */
            '.om-light{--om-bg:#f5f5f7;--om-bg2:#ececef;--om-text:#111;--om-border:rgba(0,0,0,.1);--om-card-bg:rgba(0,0,0,.04);--om-head-bg:rgba(255,255,255,.8);}',
            '.om-dark{--om-bg:#16161a;--om-bg2:#1e1e24;--om-text:#eee;--om-border:rgba(255,255,255,.08);--om-card-bg:rgba(255,255,255,.05);--om-head-bg:rgba(0,0,0,.3);}',
            '.om-overlay{position:fixed;top:0;left:0;right:0;bottom:0;width:100vw;height:100dvh;z-index:2147483647;',
            'background:var(--om-bg,var(--SmartThemeBackgroundColor,#16161a));',
            'color:var(--om-text,var(--SmartThemeBodyColor,#eee));',
            'display:flex;flex-direction:column;color:var(--SmartThemeBodyColor,#eee);',
            'animation:om-fadein .18s ease;font-size:14px;}',

            /* 主框 全屏填满 */
            '.om-box{width:100%;height:100%;min-height:0;display:flex;flex-direction:column;overflow:hidden;}',

            /* ══ 顶栏 ══ */
            '.om-head{display:flex;align-items:center;gap:8px;padding:12px 15px;flex-shrink:0;',
            'border-bottom:1px solid rgba(127,127,127,.1);background:rgba(0,0,0,.12);}',
            '.om-head-title{font-weight:700;font-size:1.05em;display:flex;align-items:center;gap:7px;flex:1;min-width:0;}',
            '.om-head-title i{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-head-actions{display:flex;align-items:center;gap:4px;}',
            '.om-icon-btn{cursor:pointer;background:none;border:none;opacity:.55;font-size:1.15em;',
            'width:34px;height:34px;border-radius:50%;display:flex;align-items:center;justify-content:center;',
            'transition:.18s;color:inherit;flex-shrink:0;}',
            '.om-icon-btn:hover{opacity:1;background:rgba(127,127,127,.12);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            /* 日夜切换 */
            '.om-theme-btn{cursor:pointer;background:rgba(127,127,127,.1);border:1px solid rgba(127,127,127,.2);',
            'border-radius:14px;padding:4px 10px;font-size:.75em;display:flex;align-items:center;gap:5px;',
            'transition:.2s;color:inherit;flex-shrink:0;height:28px;white-space:nowrap;}',
            '.om-theme-btn:hover{background:rgba(127,127,127,.2);}',,

            /* 搜索框（顶栏下方展开）*/
            '.om-search-bar{display:none;padding:8px 15px;border-bottom:1px solid rgba(127,127,127,.08);',
            'background:rgba(0,0,0,.06);flex-shrink:0;}',
            '.om-search-bar.open{display:flex;align-items:center;gap:8px;}',
            '.om-search-wrap{flex:1;position:relative;display:flex;align-items:center;}',
            '.om-search-wrap i{position:absolute;left:10px;opacity:.4;font-size:.85em;pointer-events:none;}',
            '.om-search-inp{width:100%;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);',
            'border-radius:8px;color:inherit;padding:7px 32px 7px 30px;font-size:.85em;font-family:inherit;box-sizing:border-box;}',
            '.om-search-inp:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-search-clear{background:none;border:none;color:inherit;opacity:.4;cursor:pointer;font-size:.9em;padding:4px;line-height:1;}',
            '.om-search-clear:hover{opacity:.9;}',

            /* ══ 视角切换栏 ══ */
            '.om-viewbar{display:flex;align-items:center;gap:6px;padding:8px 15px;flex-shrink:0;',
            'border-bottom:1px solid rgba(127,127,127,.08);}',
            '.om-viewtab{padding:5px 16px;border-radius:18px;font-size:.78em;cursor:pointer;white-space:nowrap;',
            'border:1px solid rgba(127,127,127,.15);background:rgba(127,127,127,.06);transition:all .15s;color:inherit;font-family:inherit;}',
            '.om-viewtab:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-viewtab.on{background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;border-color:var(--SmartThemeQuoteColor,#7c6daf);font-weight:600;}',
            '.om-char-sel{flex:1;min-width:0;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);',
            'border-radius:8px;color:inherit;padding:5px 10px;font-size:.78em;font-family:inherit;}',
            '.om-char-sel:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-char-add-btn{background:none;border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;',
            'cursor:pointer;padding:5px 10px;font-size:.78em;white-space:nowrap;font-family:inherit;}',
            '.om-char-add-btn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);}',

            /* ══ 角色选择面板 ══ */
            /* viewbar内的角色搜索框 */
            '.om-char-input{flex:1;min-width:0;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);',
            'border-radius:8px;color:inherit;padding:5px 10px;font-size:.78em;font-family:inherit;box-sizing:border-box;}',
            '.om-char-input:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-char-input::placeholder{opacity:.4;}',
            /* 下拉列表容器 */
            '.om-char-dropdown{position:absolute;left:0;right:0;top:100%;z-index:50;',
            'background:var(--om-bg,#1a1a20);border-bottom:1px solid rgba(127,127,127,.15);',
            'max-height:50vh;overflow-y:auto;box-shadow:0 4px 16px rgba(0,0,0,.2);}',
            '.om-light .om-char-dropdown{background:var(--om-bg,#f4f4f6);}',
            /* 分组标题 */
            '.om-char-group-hdr{display:flex;align-items:center;gap:6px;padding:7px 12px 4px;cursor:pointer;font-size:.78em;font-weight:600;opacity:.5;}',
            '.om-char-group-hdr:hover{opacity:.7;}',
            '.om-char-group-hdr i.om-g-arrow{font-size:.7em;transition:transform .15s;width:10px;text-align:center;}',
            '.om-char-group-hdr i.om-g-arrow.collapsed{transform:rotate(-90deg);}',
            '.om-char-group-hdr i.om-g-icon{font-size:.75em;opacity:.6;}',
            /* 角色行 */
            '.om-char-row{display:flex;align-items:center;gap:8px;padding:9px 12px 9px 20px;cursor:pointer;',
            'transition:background .1s;font-size:.9em;}',
            '.om-char-row:hover{background:rgba(127,127,127,.08);}',
            '.om-char-row.active{background:rgba(124,109,175,.1);}',
            '.om-char-star{cursor:pointer;opacity:.25;flex-shrink:0;width:20px;text-align:center;font-size:.85em;}',
            '.om-char-star.on{opacity:.8;color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-char-rname{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
            '.om-char-count{font-size:.78em;opacity:.4;flex-shrink:0;min-width:28px;text-align:right;}',
            '.om-char-actions{display:flex;gap:2px;flex-shrink:0;}',
            '.om-char-act{background:none;border:none;color:inherit;cursor:pointer;opacity:.25;font-size:.82em;padding:3px 5px;border-radius:4px;transition:.15s;}',
            '.om-char-act:hover{opacity:.85;background:rgba(127,127,127,.15);}',
            '.om-char-act.om-char-delete:hover{opacity:1;color:#e57373;background:rgba(229,115,115,.12);}',
            '.om-char-empty{text-align:center;opacity:.3;font-size:.85em;padding:18px 15px;}',

            /* ══ 分类栏 ══ */
            '.om-catbar{display:flex;gap:6px;padding:8px 15px;overflow-x:auto;flex-wrap:nowrap;flex-shrink:0;',
            '-webkit-overflow-scrolling:touch;scrollbar-width:none;',
            'border-bottom:1px solid rgba(127,127,127,.08);}',
            '.om-catbar::-webkit-scrollbar{display:none;}',
            '.om-catbtn{padding:5px 14px;border-radius:18px;font-size:.78em;cursor:pointer;white-space:nowrap;flex-shrink:0;',
            'border:1px solid rgba(127,127,127,.15);background:rgba(127,127,127,.06);transition:all .15s;color:inherit;font-family:inherit;}',
            '.om-catbtn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-catbtn.on{background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;border-color:var(--SmartThemeQuoteColor,#7c6daf);font-weight:600;}',
            '.om-catbtn-back{padding:5px 12px 5px 4px;border:none;background:none;opacity:.5;font-size:.9em;flex-shrink:0;}',
            '.om-catbtn-back:hover{opacity:1;color:var(--SmartThemeQuoteColor,#7c6daf);}',

            /* ══ 网格区（独立滚动）══ */
            '.om-grid-area{flex:1;overflow-y:auto;padding:12px 12px 8px;}',
            '.om-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(108px,1fr));gap:9px;}',

            /* ══ 添加卡片 ══ */
            '.om-add-card{border:2px dashed rgba(127,127,127,.22);border-radius:10px;',
            'display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;',
            'cursor:pointer;opacity:.55;transition:all .2s;font-size:.8em;color:inherit;}',
            '.om-add-card:hover{opacity:1;border-color:var(--SmartThemeQuoteColor,#7c6daf);',
            'color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.04);}',
            '.om-add-card i{font-size:1.4em;}',

            /* ══ 穿搭卡片 ══ */
            '.om-card{border-radius:10px;overflow:hidden;position:relative;cursor:pointer;',
            'transition:all .18s;border:2px solid transparent;display:flex;flex-direction:column;}',
            '.om-card:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(0,0,0,.25);}',
            '.om-card.on{border-color:var(--SmartThemeQuoteColor,#7c6daf);',
            'box-shadow:0 0 0 1px var(--SmartThemeQuoteColor,#7c6daf),0 4px 16px rgba(0,0,0,.2);}',
            /* 图片区 */
            '.om-card-img{width:100%;aspect-ratio:3/4;position:relative;background:rgba(127,127,127,.1);',
            'display:flex;align-items:center;justify-content:center;overflow:hidden;flex-shrink:0;}',
            '.om-card-img img{width:100%;height:100%;object-fit:cover;display:block;}',
            /* 底部渐变文字遮罩 */
            /* 触屏：点击过的卡片菜单常显 */
            '@media (hover:none){.om-card-menu{opacity:.75 !important;}}',
            '.om-card-info{padding:5px 7px 6px;background:var(--om-card-bg,rgba(127,127,127,.06));min-height:36px;box-sizing:border-box;}',
            '.om-card-name{font-size:.8em;font-weight:600;line-height:1.3;',
            'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;',
            'color:var(--om-text,#eee);}',
            '.om-card-tag{font-size:.68em;line-height:1.2;margin-top:2px;',
            'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;',
            'color:var(--om-text,#aaa);opacity:.5;}',
            /* 无图片占位 - 显示描述摘要 */
            '.om-card-noimg{display:flex;flex-direction:column;align-items:flex-start;gap:5px;',
            'width:100%;height:100%;justify-content:flex-start;padding:12px 12px 32px 12px;box-sizing:border-box;',
            'background:linear-gradient(135deg,rgba(127,127,127,.08) 0%,rgba(127,127,127,.03) 100%);}',
            '.om-card-noimg .om-noimg-name{font-size:.88em;font-weight:700;line-height:1.3;',
            'display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;',
            'word-break:break-all;color:var(--om-text,#eee);}',
            '.om-card-noimg .om-noimg-desc{font-size:.78em;line-height:1.45;opacity:.55;',
            'display:-webkit-box;-webkit-line-clamp:8;-webkit-box-orient:vertical;overflow:hidden;',
            'word-break:break-all;color:var(--om-text,#ccc);}',
            '.om-card-noimg .om-noimg-icon{font-size:1.2em;opacity:.2;position:absolute;bottom:8px;right:8px;}',
            /* 有文字描述但无图片时显示背景 */
            '.om-card.no-img{background:var(--om-card-bg,rgba(127,127,127,.06));}',
            '.om-card.no-img .om-card-info{display:none;}',
            '.om-card.no-img .om-card-img{aspect-ratio:unset;flex:1;min-height:0;}',
            /* 选中角标 */
            '.om-badge-on{position:absolute;top:5px;right:5px;',
            'width:20px;height:20px;border-radius:50%;',
            'background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;',
            'display:flex;align-items:center;justify-content:center;font-size:.6em;',
            'box-shadow:0 2px 6px rgba(0,0,0,.3);}',
            /* 批量选择框 */
            '.om-card-check{position:absolute;top:5px;left:5px;',
            'width:20px;height:20px;border-radius:6px;border:2px solid rgba(255,255,255,.7);',
            'background:rgba(0,0,0,.3);display:flex;align-items:center;justify-content:center;',
            'cursor:pointer;transition:.15s;z-index:2;}',
            '.om-card-check.checked{background:var(--SmartThemeQuoteColor,#7c6daf);border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-card-check i{font-size:.65em;color:#fff;opacity:0;transition:.12s;}',
            '.om-card-check.checked i{opacity:1;}',
            '.om-card.batch-sel{border:2px solid var(--SmartThemeQuoteColor,#7c6daf);}',

            /* 卡片菜单按钮 - 右下角，不与对号冲突 */
            '.om-card-menu{position:absolute;bottom:5px;right:5px;',
            'width:20px;height:20px;border-radius:50%;',
            'background:rgba(0,0,0,.5);color:#fff;border:none;cursor:pointer;',
            'display:flex;align-items:center;justify-content:center;font-size:.55em;line-height:1;overflow:hidden;',
            'opacity:0;transition:opacity .18s;z-index:3;pointer-events:auto;',
            'backdrop-filter:blur(4px);box-shadow:0 2px 6px rgba(0,0,0,.3);}',
            '.om-card:hover .om-card-menu,.om-card:active .om-card-menu{opacity:1;}',
            '.om-card-menu:hover{background:rgba(0,0,0,.75);}',

            /* ══ 批量操作栏（网格区顶部，随滚动）══ */
            '.om-batch-bar{display:flex;align-items:center;gap:6px;padding:8px 10px;',
            'background:rgba(124,109,175,.08);border:1px solid rgba(124,109,175,.2);',
            'border-radius:10px;margin-bottom:10px;flex-wrap:nowrap;overflow-x:auto;',
            '-webkit-overflow-scrolling:touch;scrollbar-width:none;}',
            '.om-batch-bar::-webkit-scrollbar{display:none;}',
            '.om-batch-info{font-size:.82em;font-weight:600;color:var(--SmartThemeQuoteColor,#7c6daf);white-space:nowrap;flex-shrink:0;}',
            '.om-batch-acts{display:flex;gap:5px;flex-shrink:0;flex-wrap:nowrap;}',
            '.om-batch-btn{padding:5px 10px;border-radius:6px;border:1px solid rgba(127,127,127,.2);',
            'background:rgba(127,127,127,.07);color:inherit;cursor:pointer;font-size:.78em;',
            'font-family:inherit;transition:.15s;white-space:nowrap;flex-shrink:0;}',
            '.om-batch-btn:hover{background:rgba(127,127,127,.15);border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-batch-btn.danger{color:#e57373;border-color:rgba(229,115,115,.35);}',
            '.om-batch-btn.danger:hover{background:#e57373;color:#fff;border-color:#e57373;}',

            /* 空状态 */
            '.om-empty{text-align:center;padding:40px 0;opacity:.45;display:flex;flex-direction:column;gap:10px;align-items:center;font-size:.88em;}',
            '.om-empty i{font-size:2.6em;}',

            /* ══ 底栏 ══ */
            '.om-bottombar{display:flex !important;align-items:center;gap:6px;padding:10px 14px;flex-shrink:0;',
            'border-top:1px solid rgba(127,127,127,.1);background:rgba(0,0,0,.12);}',
            '.om-bottom-status{flex:1;min-width:0;display:flex;align-items:center;gap:7px;',
            'cursor:pointer;border-radius:8px;padding:5px 7px;transition:.15s;',
            'border:1px solid transparent;}',
            '.om-bottom-status:hover{background:rgba(127,127,127,.08);border-color:rgba(127,127,127,.12);}',
            '.om-status-dot{width:8px;height:8px;border-radius:50%;flex-shrink:0;}',
            '.om-status-dot.gray{background:rgba(127,127,127,.5);}',
            '.om-status-dot.green{background:#4caf50;}',
            '.om-status-dot.orange{background:#ff8c42;}',
            '.om-status-text{font-size:.82em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;opacity:.9;}',
            '.om-status-clear{margin-left:4px;background:none;border:none;font-size:.75em;color:inherit;',
            'opacity:.5;cursor:pointer;white-space:nowrap;padding:2px 5px;border-radius:4px;font-family:inherit;flex-shrink:0;}',
            '.om-status-clear:hover{opacity:1;background:rgba(127,127,127,.1);}',
            '.om-bottom-btn{width:36px;height:36px;border-radius:50%;border:1px solid rgba(127,127,127,.15);',
            'background:rgba(127,127,127,.06);color:inherit;cursor:pointer;',
            'display:flex;align-items:center;justify-content:center;font-size:.9em;',
            'transition:.18s;flex-shrink:0;}',
            '.om-bottom-btn:hover{background:rgba(127,127,127,.15);border-color:var(--SmartThemeQuoteColor,#7c6daf);',
            'color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-batch-toggle-btn{padding:6px 11px;border-radius:18px;border:1px solid rgba(127,127,127,.2);',
            'background:rgba(127,127,127,.07);color:inherit;cursor:pointer;font-size:.75em;',
            'white-space:nowrap;font-family:inherit;transition:.15s;flex-shrink:0;}',
            '.om-batch-toggle-btn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-batch-toggle-btn.on{background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',

            /* ══ 选择详情面板（从底栏上方弹出）══ */
            '.om-detail-panel{position:absolute;bottom:0;left:0;right:0;',
            'background:var(--om-bg2,var(--SmartThemeBackgroundColor,rgba(28,28,32,1)));',
            'border-radius:16px 16px 0 0;padding:14px 16px 16px;',
            'box-shadow:0 -4px 24px rgba(0,0,0,.3);',
            'animation:om-sheet-up .22s ease;border-top:1px solid rgba(127,127,127,.15);}',
            '.om-detail-handle{width:32px;height:4px;border-radius:2px;',
            'background:rgba(127,127,127,.25);margin:0 auto 12px;}',
            '.om-detail-title{font-size:.78em;font-weight:700;opacity:.55;text-transform:uppercase;letter-spacing:.06em;margin-bottom:10px;}',
            '.om-detail-tags{display:flex;flex-wrap:wrap;gap:6px;}',
            '.om-detail-tag{display:inline-flex;align-items:center;gap:5px;',
            'padding:4px 6px 4px 10px;border-radius:14px;',
            'background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;font-size:.78em;font-weight:600;}',
            '.om-detail-tag-x{background:none;border:none;color:#fff;cursor:pointer;',
            'font-size:.9em;line-height:1;padding:0 2px;opacity:.75;font-family:inherit;}',
            '.om-detail-tag-x:hover{opacity:1;}',

            /* ══ Bottom Sheet 通用 ══ */
            '.om-sheet-overlay{position:absolute !important;inset:0 !important;z-index:1 !important;background:rgba(0,0,0,.45) !important;pointer-events:auto !important;}',
            '.om-sheet{position:absolute;bottom:0;left:0;right:0;max-height:88vh;max-height:88dvh;',
            'background:var(--om-bg2,var(--SmartThemeBackgroundColor,#1a1a1e));',
            'color:var(--om-text,var(--SmartThemeBodyColor,#eee));',
            'border-radius:18px 18px 0 0;overflow-y:auto;',
            'animation:om-sheet-up .25s ease;border:1px solid rgba(127,127,127,.15);border-bottom:none;}',
            '.om-sheet-handle{width:36px;height:4px;border-radius:2px;',
            'background:rgba(127,127,127,.25);margin:10px auto 4px;}',
            '.om-sheet-content{padding:4px 20px 32px;}',
            '.om-sheet-title{font-weight:700;font-size:1.05em;padding:10px 0 14px;',
            'display:flex;align-items:center;gap:8px;}',
            '.om-sheet-title i{color:var(--SmartThemeQuoteColor,#7c6daf);}',

            /* ══ 长按操作菜单 Bottom Sheet ══ */
            '.om-ctx-item{display:flex;align-items:center;gap:12px;padding:14px 4px;',
            'cursor:pointer;border-bottom:1px solid rgba(127,127,127,.08);transition:.15s;border-radius:0;}',
            '.om-ctx-item:last-child{border-bottom:none;}',
            '.om-ctx-item:hover{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-ctx-item i{width:20px;text-align:center;opacity:.75;font-size:1em;}',
            '.om-ctx-item.danger{color:#e57373;}',
            '.om-ctx-item.danger:hover{color:#ef5350;}',
            '.om-ctx-outfit-name{font-size:.85em;opacity:.5;padding:2px 0 10px;',
            'border-bottom:1px solid rgba(127,127,127,.1);margin-bottom:4px;}',

            /* ══ 通用组件 ══ */
            '.om-sec-title{font-size:.75em;font-weight:700;opacity:.55;text-transform:uppercase;',
            'letter-spacing:.07em;padding:10px 0 7px;}',
            '.om-divider{height:1px;background:rgba(127,127,127,.12);margin:6px 0 12px;}',
            '.om-hint{font-size:.76em;opacity:.5;line-height:1.4;}',
            '.om-btn-row{display:flex;gap:8px;flex-wrap:wrap;}',
            '.om-btn{padding:8px 16px;border-radius:8px;border:none;cursor:pointer;',
            'font-size:.87em;font-weight:600;transition:.18s;font-family:inherit;}',
            '.om-btn-safe{background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;}',
            '.om-btn-safe:hover{filter:brightness(1.1);box-shadow:0 3px 10px rgba(0,0,0,.15);}',
            '.om-btn-outline{background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.22);color:inherit;}',
            '.om-btn-outline:hover{background:rgba(127,127,127,.15);border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-btn-danger{background:rgba(229,115,115,.1);border:1px solid #e57373;color:#e57373;}',
            '.om-btn-danger:hover{background:#e57373;color:#fff;}',
            /* 输入 */
            '.om-setting-row{display:flex;flex-direction:column;gap:5px;margin-bottom:4px;}',
            '.om-setting-row label{font-size:.8em;opacity:.7;}',
            '.om-setting-row select,.om-setting-row textarea{background:rgba(127,127,127,.08);',
            'border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;',
            'padding:7px 10px;font-size:.85em;width:100%;box-sizing:border-box;resize:vertical;font-family:inherit;}',
            '.om-setting-row select:focus,.om-setting-row textarea:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-row-inline{flex-direction:row!important;align-items:center;justify-content:space-between;}',
            '.om-row-inline label{opacity:.8;font-size:.88em;}',
            '.om-chk{width:17px;height:17px;accent-color:var(--SmartThemeQuoteColor,#7c6daf);cursor:pointer;}',
            '.om-storage-info{font-size:.72em;opacity:.45;padding:4px 0;}',
            /* 编辑表单 */
            '.om-field{display:flex;flex-direction:column;gap:5px;margin-bottom:10px;}',
            '.om-field label{font-size:.8em;opacity:.7;font-weight:500;}',
            '.om-field input[type=text],.om-field select,.om-field textarea{',
            'background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);',
            'border-radius:8px;color:inherit;padding:9px 11px;font-size:.9em;width:100%;box-sizing:border-box;font-family:inherit;}',
            '.om-field textarea{resize:none;}',
            '.om-field input:focus,.om-field select:focus,.om-field textarea:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-frow{display:flex;gap:7px;align-items:stretch;}',
            '.om-frow select{flex:1;}',
            '.om-imgarea{width:100%;height:160px;background:rgba(127,127,127,.06);',
            'border:2px dashed rgba(127,127,127,.25);border-radius:10px;',
            'display:flex;align-items:center;justify-content:center;cursor:pointer;overflow:hidden;transition:border-color .18s;}',
            '.om-imgarea:hover,.om-imgarea.drag{border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.1);}',
            '.om-imgph{display:flex;flex-direction:column;align-items:center;gap:6px;opacity:.4;font-size:.82em;pointer-events:none;}',
            '.om-imgph i{font-size:1.8em;}',
            '.om-imgarea img{width:100%;height:100%;object-fit:contain;}',
            '.om-img-actions{display:flex;gap:7px;margin-top:7px;}',
            '.om-edit-foot{display:flex;gap:9px;justify-content:flex-end;padding-top:14px;',
            'border-top:1px solid rgba(127,127,127,.1);margin-top:10px;}',
            /* 场景标签建议 */
            '.om-suggest-wrap{position:relative;width:100%;}',
            '.om-suggest-wrap input{width:100%;box-sizing:border-box;}',
            '.om-suggest-list{position:absolute;top:100%;left:0;right:0;',
            'background:var(--om-bg2,var(--SmartThemeBackgroundColor,rgba(40,40,40,.98)));',
            'border:1px solid rgba(127,127,127,.22);border-radius:8px;margin-top:3px;',
            'z-index:200;max-height:160px;overflow-y:auto;box-shadow:0 6px 20px rgba(0,0,0,.25);}',
            '.om-suggest-item{padding:8px 12px;font-size:.85em;cursor:pointer;transition:.12s;color:var(--SmartThemeBodyColor,inherit);}',
            '.om-suggest-item:hover{background:rgba(127,127,127,.15);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            /* ══ 标签管理面板 ══ */
            '.om-tagpanel{max-height:55vh;display:flex;flex-direction:column;gap:8px;}',
            '.om-tagpanel-search{width:100%;box-sizing:border-box;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;padding:8px 11px;font-size:.85em;font-family:inherit;}',
            '.om-tagpanel-search:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-tagpanel-list{flex:1;overflow-y:auto;min-height:0;display:flex;flex-direction:column;gap:4px;}',
            '.om-tagpanel-item{display:flex;align-items:center;gap:8px;padding:10px 12px;background:rgba(127,127,127,.06);border-radius:9px;border:1px solid rgba(127,127,127,.1);transition:all .15s;cursor:grab;user-select:none;-webkit-user-select:none;}',
            '.om-tagpanel-item:active{cursor:grabbing;}',
            '.om-tagpanel-item.dragging{opacity:.5;border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(124,109,175,.08);}',
            '.om-tagpanel-item.drag-over{border-top:2px solid var(--SmartThemeQuoteColor,#7c6daf);padding-top:9px;}',
            '.om-tagpanel-grip{opacity:.25;font-size:.8em;flex-shrink:0;cursor:grab;}',
            '.om-tagpanel-name{flex:1;font-size:.88em;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
            '.om-tagpanel-count{font-size:.74em;opacity:.45;flex-shrink:0;}',
            '.om-tagpanel-acts{display:flex;gap:2px;flex-shrink:0;}',
            '.om-tagpanel-use{background:none;border:none;color:var(--SmartThemeQuoteColor,#7c6daf);cursor:pointer;font-size:.78em;padding:3px 8px;border-radius:4px;transition:.15s;font-family:inherit;}',
            '.om-tagpanel-use:hover{background:rgba(124,109,175,.12);}',
            '.om-tagpanel-del{background:none;border:none;color:inherit;cursor:pointer;opacity:.25;font-size:.78em;padding:3px 5px;border-radius:4px;transition:.15s;}',
            '.om-tagpanel-del:hover{opacity:1;color:#e57373;background:rgba(229,115,115,.12);}',
            '.om-tagpanel-empty{text-align:center;opacity:.3;font-size:.85em;padding:18px 0;}',
            '.om-tagpanel-add{display:flex;gap:8px;flex-shrink:0;}',
            '.om-tagpanel-add input{flex:1;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;padding:8px 11px;font-size:.85em;font-family:inherit;box-sizing:border-box;}',
            '.om-tagpanel-add input:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-tag-expand-btn{background:rgba(127,127,127,.06);border:1px solid rgba(127,127,127,.18);border-radius:8px;color:inherit;cursor:pointer;padding:7px 11px;font-size:.78em;font-family:inherit;transition:.15s;display:flex;align-items:center;gap:5px;white-space:nowrap;}',
            '.om-tag-expand-btn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.1);}',
            /* 分类管理 */
            '.om-cat-item{display:flex;align-items:center;gap:8px;padding:9px 12px;',
            'background:rgba(127,127,127,.06);border-radius:9px;',
            'border:1px solid rgba(127,127,127,.1);transition:all .15s;margin-bottom:7px;}',
            '.om-cat-item:hover{background:rgba(127,127,127,.11);}',
            '.om-cat-chevron{font-size:.65em;opacity:.35;flex-shrink:0;width:12px;text-align:center;transition:transform .15s;}',
            '.om-cat-chevron-placeholder{width:12px;flex-shrink:0;}',
            '.om-cat-name{flex:1;font-size:.88em;}',
            '.om-cat-count{font-size:.74em;opacity:.45;}',
            '.om-cat-add-row{display:flex;gap:8px;}',
            '.om-cat-add-row input{flex:1;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);',
            'border-radius:8px;color:inherit;padding:8px 11px;font-size:.88em;font-family:inherit;box-sizing:border-box;}',
            '.om-cat-add-row input:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            /* 预设 */
            '.om-preset-item{display:flex;align-items:center;gap:8px;padding:10px 14px;',
            'background:rgba(127,127,127,.06);border-radius:9px;border:1px solid rgba(127,127,127,.1);',
            'transition:all .15s;cursor:pointer;margin-bottom:7px;}',
            '.om-preset-item:hover{background:rgba(127,127,127,.12);border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-preset-name{flex:1;font-size:.9em;font-weight:600;}',
            '.om-preset-count{font-size:.74em;opacity:.5;white-space:nowrap;}',
            '.om-preset-item.current{border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(124,109,175,.08);}',
            /* 通用小按钮 */
            '.om-btn-sm{padding:5px 7px;border-radius:6px;cursor:pointer;font-size:.78em;',
            'background:rgba(127,127,127,.07);border:1px solid rgba(127,127,127,.14);',
            'transition:all .15s;color:inherit;font-family:inherit;}',
            '.om-btn-sm:hover{background:rgba(127,127,127,.15);}',
            /* 导出/导入 modal */
            '.om-modal{position:absolute;inset:0;z-index:2;background:rgba(0,0,0,.45);pointer-events:auto;',
            'display:flex;align-items:center;justify-content:center;padding:20px;box-sizing:border-box;}',
            '.om-modal-box{background:var(--om-bg2,var(--SmartThemeBackgroundColor,rgba(30,30,30,1)));',
            'color:var(--om-text,var(--SmartThemeBodyColor,#eee));border-radius:16px;padding:22px 20px 26px;',
            'width:100%;max-width:400px;max-height:85vh;overflow-y:auto;',
            'display:flex;flex-direction:column;gap:10px;',
            'box-shadow:0 8px 32px rgba(0,0,0,.4);margin:auto;border:1px solid rgba(127,127,127,.15);}',
            '.om-modal-title{font-weight:700;font-size:1em;margin-bottom:4px;}',
            '.om-modal-btn{padding:10px 14px;border-radius:9px;border:1px solid rgba(127,127,127,.2);',
            'background:rgba(127,127,127,.07);color:inherit;cursor:pointer;font-size:.88em;text-align:left;',
            'font-family:inherit;transition:.15s;}',
            '.om-modal-btn:hover{background:rgba(127,127,127,.16);border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.om-modal-cancel{padding:9px;border-radius:9px;border:none;background:none;',
            'color:inherit;cursor:pointer;font-size:.85em;opacity:.5;font-family:inherit;margin-top:4px;}',
            '.om-modal-cancel:hover{opacity:1;}',
            /* 全屏 lightbox */
            '.om-lightbox{position:absolute;inset:0;z-index:3;background:rgba(0,0,0,.92);pointer-events:auto;',
            'display:flex;align-items:center;justify-content:center;animation:om-popin .18s ease;}',
            '.om-lb-img{max-width:92vw;max-height:88vh;object-fit:contain;border-radius:10px;',
            'box-shadow:0 8px 40px rgba(0,0,0,.6);user-select:none;}',
            '.om-lb-close{position:absolute;top:18px;right:20px;background:rgba(255,255,255,.12);',
            'border:none;color:#fff;font-size:1.3em;width:40px;height:40px;border-radius:50%;',
            'cursor:pointer;display:flex;align-items:center;justify-content:center;transition:.15s;z-index:2147483647;}',
            '.om-lb-close:hover{background:rgba(255,255,255,.25);}',
            '.om-lb-nav{position:absolute;top:50%;transform:translateY(-50%);background:rgba(255,255,255,.12);',
            'border:none;color:#fff;font-size:1.2em;width:42px;height:42px;border-radius:50%;',
            'cursor:pointer;display:flex;align-items:center;justify-content:center;transition:.15s;z-index:2147483647;}',
            '.om-lb-nav:hover{background:rgba(255,255,255,.25);}',
            '.om-lb-prev{left:14px;} .om-lb-next{right:14px;}',
            '.om-lb-counter{position:absolute;bottom:20px;left:50%;transform:translateX(-50%);',
            'color:rgba(255,255,255,.6);font-size:.82em;background:rgba(0,0,0,.4);',
            'padding:4px 14px;border-radius:20px;z-index:2147483647;}',
            '.om-lb-name{position:absolute;top:20px;left:50%;transform:translateX(-50%);',
            'color:#fff;font-size:.9em;font-weight:600;background:rgba(0,0,0,.4);',
            'padding:5px 16px;border-radius:20px;max-width:60vw;white-space:nowrap;',
            'overflow:hidden;text-overflow:ellipsis;z-index:2147483647;}',
        ].join('');
        document.head.appendChild(s);
    }
